
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "leftSUMARESTAleftMULTDIVMODDIV INTEGER MOD MULT RESTA SUMA\n        calculadora :   calculadora sentence \n                        | empty\n        \n        sentence : expr ';'\n        \n        sentence : empty ';'\n        \n        expr : '(' expr ')'\n              | expr SUMA expr\n              | expr RESTA expr\n              | expr MULT expr\n              | expr DIV expr\n              | expr MOD expr\n              | INTEGER\n        empty :"
    
_lr_action_items = {'(':([0,1,2,3,6,8,9,10,11,12,13,14,],[-12,6,-2,-1,6,-3,6,6,6,6,6,-4,]),'INTEGER':([0,1,2,3,6,8,9,10,11,12,13,14,],[-12,7,-2,-1,7,-3,7,7,7,7,7,-4,]),'$end':([0,1,2,3,8,14,],[-12,0,-2,-1,-3,-4,]),';':([0,1,2,3,4,5,7,8,14,16,17,18,19,20,21,],[-12,-12,-2,-1,8,14,-11,-3,-4,-6,-7,-8,-9,-10,-5,]),'SUMA':([4,7,15,16,17,18,19,20,21,],[9,-11,9,-6,-7,-8,-9,-10,-5,]),'RESTA':([4,7,15,16,17,18,19,20,21,],[10,-11,10,-6,-7,-8,-9,-10,-5,]),'MULT':([4,7,15,16,17,18,19,20,21,],[11,-11,11,11,11,-8,-9,-10,-5,]),'DIV':([4,7,15,16,17,18,19,20,21,],[12,-11,12,12,12,-8,-9,-10,-5,]),'MOD':([4,7,15,16,17,18,19,20,21,],[13,-11,13,13,13,-8,-9,-10,-5,]),')':([7,15,16,17,18,19,20,21,],[-11,21,-6,-7,-8,-9,-10,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calculadora':([0,],[1,]),'empty':([0,1,],[2,5,]),'sentence':([1,],[3,]),'expr':([1,6,9,10,11,12,13,],[4,15,16,17,18,19,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calculadora","S'",1,None,None,None),
  ('calculadora -> calculadora sentence','calculadora',2,'p_calculadora','p2.py',32),
  ('calculadora -> empty','calculadora',1,'p_calculadora','p2.py',33),
  ('sentence -> expr ;','sentence',2,'p_sentencia','p2.py',38),
  ('sentence -> empty ;','sentence',2,'p_sentencia_buida','p2.py',46),
  ('expr -> ( expr )','expr',3,'p_expr','p2.py',52),
  ('expr -> expr SUMA expr','expr',3,'p_expr','p2.py',53),
  ('expr -> expr RESTA expr','expr',3,'p_expr','p2.py',54),
  ('expr -> expr MULT expr','expr',3,'p_expr','p2.py',55),
  ('expr -> expr DIV expr','expr',3,'p_expr','p2.py',56),
  ('expr -> expr MOD expr','expr',3,'p_expr','p2.py',57),
  ('expr -> INTEGER','expr',1,'p_expr','p2.py',58),
  ('empty -> <empty>','empty',0,'p_empty','p2.py',69),
]
